### ISSUE TITLE
Javac.exe not present on Windows x64 in JRE 8

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [jsdevel/node-find-java-home#10]
Hello, 

I was trying to deploy Kibi (a Kibana fork) which relies on the  `JBDC` package which relies on the `JAVA` package which relies on `find-java-home`. I installed `jre1.8.0_102` on Windows 7 x64 and `javac.exe` was not part on the install, as a result find-java-home failed to recognize my correctly set `JAVA_HOME` environment variable and nothing worked. I worked around the issue (See sirensolutions/kibi#52 ) but it is still a concern.

As far as i can tell this file is only part of the JDK, not the JRE installation on windows now (not sure about 32-bit). Is it possible to pick another file to test the folder?

Here is a list of the files that are installed in `\Program Files\jre1.8.0_102\bin\` by default by JRE 1.8.0-102 x64 on Windows 7 x64:

dtplugin
plugin2
server
awt.dll
bci.dll
dcpr.dll
decora_sse.dll
deploy.dll
dt_shmem.dll
dt_socket.dll
eula.dll
fontmanager.dll
fxplugins.dll
glass.dll
glib-lite.dll
gstreamer-lite.dll
hprof.dll
instrument.dll
j2pcsc.dll
j2pkcs11.dll
jaas_nt.dll
jabswitch.exe
java-rmi.exe
java.dll
java.exe
JavaAccessBridge-64.dll
javacpl.cpl
javacpl.exe
javafx_font.dll
javafx_font_t2k.dll
javafx_iio.dll
javaw.exe
javaws.exe
java_crw_demo.dll
jawt.dll
JAWTAccessBridge-64.dll
jdwp.dll
jfr.dll
jfxmedia.dll
jfxwebkit.dll
jjs.exe
jli.dll
jp2iexp.dll
jp2launcher.exe
jp2native.dll
jp2ssv.dll
jpeg.dll
jsdt.dll
jsound.dll
jsoundds.dll
kcms.dll
keytool.exe
kinit.exe
klist.exe
ktab.exe
lcms.dll
management.dll
mlib_image.dll
msvcp120.dll
msvcr100.dll
msvcr120.dll
net.dll
nio.dll
npt.dll
orbd.exe
pack200.exe
policytool.exe
prism_common.dll
prism_d3d.dll
prism_sw.dll
resource.dll
rmid.exe
rmiregistry.exe
servertool.exe
splashscreen.dll
sqljdbc_auth.dll
ssv.dll
ssvagent.exe
sunec.dll
sunmscapi.dll
t2k.dll
tnameserv.exe
unpack.dll
unpack200.exe
verify.dll
w2k_lsa_auth.dll
WindowsAccessBridge-64.dll
wsdetect.dll
zip.dll

**Comment by AlgorithmsAreCool** [comment]
Anybody home?

**Comment by jvilk** [comment]
@AlgorithmsAreCool You are correct; `javac` is only present as part of the JDK. 

If this is still an issue, and the folks behind this package aren't maintaining it, you could try my package [`locate-java-home`](https://github.com/jvilk/locate-java-home). The goal is a little different -- `locate-java-home` will find *all* Java installations, including non-default ones -- but it might be useful for your project.

**Comment by AlgorithmsAreCool** [comment]
Thanks, i'll relay your package back to the kibi team.

**Comment by jsdevel** [comment]
sorry for the late reply.  Is this issue still present @AlgorithmsAreCool?

**Comment by AlgorithmsAreCool** [comment]
@jsdevel 

Yep

**Comment by jsdevel** [comment]
@AlgorithmsAreCool have you tried installing the JDK?

**Comment by AlgorithmsAreCool** [comment]
@jsdevel 
Well....about that,
as far as i can tell find-java-home looks for javac.exe to test for JAVA_HOME. But that file isn't in a normal JRE installation, just in the full SDK. So unless you have the Java SDK installed (not common for a production box) find-java-home fails.

**Comment by AlgorithmsAreCool** [comment]
I believe that installing the JDK would fix the problem yes, but that isn't always a great solution for a production box.

**Comment by jsdevel** [comment]
@AlgorithmsAreCool originally this was created for the `java` module.  JDK was required there.  Perhaps we could add an option to simply search for `java` instead of `javac` if `{ jre: true }` is given?

**Comment by AlgorithmsAreCool** [comment]
That makes sense, but i wonder if the JDK is still required fully by the `java` module. In my testing i got everything to work by adding an empty `javac.exe` file in my JAVA_HOME directory and the project (`kibi`) appeared to work just fine.

**Comment by AlgorithmsAreCool** [comment]
I can follow up with the `java` folks to figure out the best solution

**Comment by jsdevel** [comment]
OK.  Let me know what you find.  If we need to add support for JRE here then that's definitely an option.  Thanks @AlgorithmsAreCool !

**Comment by jsdevel** [comment]
i'm closing this.  feel free to reopen if it's still an issue.
