### ISSUE TITLE
Getting JAVA_HOME from registry is not working

### ISSUE THREAD

**Issue by lazyjin** [jsdevel/node-find-java-home#14]
Hello.

I have tried to retrieve JAVA_HOME from windows that is not set JAVA_HOME evn.
I works well on test code, but not working on my app.
My app need to get JAVA_HOME first, so i wrote code like below.

**initJvmPath.js**
```
module.exports = require('find-java-home')(function(err, home) {
    if (home) {
        dll = glob.sync('**/jvm.dll', {
            cwd: home
        })[0];

        binary = dll;

        fs.writeFileSync(
            path.resolve(__dirname, '../node_modules/java/build/jvm_dll_path.json'),
            binary ? JSON.stringify(
                path.delimiter + path.dirname(path.resolve(home, binary))
            ) : '""'
        );
    }

    return true;
});
```

**main.js**
```
// initialize & set java jvm path
require('./initJavaPath.js');
require('./ipcHandler');

// main code below
...

```
In my app, findJavaHome() return null, so I checked the code and noticed findInRegistry() always return null at [line 110](https://github.com/jsdevel/node-find-java-home/blob/master/index.js#L110).
It's because winreg is async, keysFound.length is 0 when it checked at line 110.

**Comment by jsdevel** [comment]
@lazyjin I'm thinking the JAVA_HOME value may be in a different place in your registry.  On [line 122](https://github.com/jsdevel/node-find-java-home/blob/master/index.js#L122) you can see that the registry value is returned if it is found.

**Comment by lazyjin** [comment]
@jsdevel Here's my env var and registry.

```
C:\node-find-java-home>echo %JAVA_HOME%
%JAVA_HOME%

C:\node-find-java-home>reg query hklm\SOFTWARE\JavaSoft

HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit
HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Plug-in
HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment
HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Update
HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Web Start
HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Web Start Caps

C:\node-find-java-home>reg query "hklm\SOFTWARE\JavaSoft\Java Development Kit"

HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit
    CurrentVersion    REG_SZ    1.8

HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit\1.8
HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Development Kit\1.8.0_101

C:\node-find-java-home>
```
I installed JAVA as default, and found it never runs line 122 with this env.  
findInRegistry() always returns before WinReg.key() does. 

And I think the code below does not work properly.
```
var keyPath = paths.forEach(function(element) {
    var key = new WinReg({ key: keyPath });
    key.keys(function(err, javaKeys){
      keysFound.concat(javaKeys);
    });
  }, this)
```
forEach returns undifined, but keyPath is used for WinReg's arg.

**Comment by jsdevel** [comment]
hmm.  It looks like the value of `JAVA_HOME` is set to `%JAVA_HOME%`.  Is that correct?

**Comment by lazyjin** [comment]
Yes. It's windows command prompt. It just echo arg when env var is not set.

**Comment by jsdevel** [comment]
I see.  Not sure what it would be.

**Comment by wsw0108** [comment]
It is because winreg Registry's methods are not sync, because `spawn` is not sync.

**Comment by jsdevel** [comment]
PRs are welcome.  I don't have the time to test this on a windows VM at the moment.

**Comment by jsdevel** [comment]
i'm closing this.  feel free to re-open if it's still an issue.
