### ISSUE TITLE
Cannot find oracle jdk from windows registry

### ISSUE THREAD

**Issue by Eskibear** [jsdevel/node-find-java-home#19]
First I want to thank you for the convenient libary. But I do find below problems:

### missing leading slash in key 
https://github.com/jsdevel/node-find-java-home/blob/6a72df699d9ffa51858833f2688dcef4f812be66/index.js#L58
I have to add the leading slash to get it work, i.e. `\\SOFTWARE....` 

### early return of `findInRegistry`
It always returns `null`, without waiting for callback to execute.
https://github.com/jsdevel/node-find-java-home/blob/6a72df699d9ffa51858833f2688dcef4f812be66/index.js#L102-L110

### new registry key for JDK 11/12
For Oracle JDK 11/12, it uses a new key `SOFTWARE\\JavaSoft\\JDK`.

Can you kindly fix these?

**Comment by Eskibear** [comment]
> Can you kindly fix these?

My work is currently blocked by this issue, and I tried to fix it by myself but the JS callback hell just... Is there any possibility to get the issue fixed recently? I don't want to re-invent the wheel if someone can fix it. 
Thanks in advance.

**Comment by jsdevel** [comment]
I'm sorry, but this is an open source project that I am not getting paid to support. I am happy to review pull requests and merge code and publish this module, but you will have to fix this on your own to help the community.

**Comment by Eskibear** [comment]
I would have sent out the PR if I was able to create it.
JS with callback hell is too hard to maintain (at least for me), and now there's more elegant way to handle async functions in JS world. If you do want me to fix the issue, I have to rewrite the whole project in TS. Are you willing to accept that kind of PR?

**Comment by jsdevel** [comment]
@Eskibear i'm totally cool with refactoring the project to TS!  If possible though, can you do that first before fixing your issue?  that way it's easier to track what exactly changed.

this was written when node v0.10 was the stable version...
