### ISSUE TITLE
Support jenv style java version definition

### ISSUE THREAD

**Issue by timolehto** [jsdevel/node-find-java-home#25]
Use `.java-version` and check if `$HOME/.jenv/versions/$(cat .java-version)` would contain appropriate jdk installation for OS X and LInux. This was originally reported as a feature request on vscode https://github.com/microsoft/vscode-java-debug/issues/650

**Comment by jsdevel** [comment]
@timolehto feel free to open a pr

**Comment by timolehto** [comment]
Here you go @jsdevel

**Comment by timolehto** [comment]
@jsdevel planning on making 1.1 release any time soonish? Would love to make a PR to visual code java support to upgrade `node-find-java-home` and benefit from this newly merged `jenv` support (as a bonus also also there's the extended windows registry support too).

**Comment by jsdevel** [comment]
@timolehto 1.1.0 has been published.  thank you for your support!

**Comment by jsdevel** [comment]
@timolehto can you please close this issue once you've verified that it works?

**Comment by timolehto** [comment]
I think we can close this now @jsdevel and should there be some issues with I can reopen.
