### ISSUE TITLE
Cannot redeclare exported variable 'promise' with version 1.2.0

### ISSUE THREAD

**Issue by apupier** [jsdevel/node-find-java-home#31]
When tryign to upgrade from 1.1 to 1.2, this compilation error appears:

```
node_modules/find-java-home/dist/index.d.ts:11:9 - error TS2323: Cannot redeclare exported variable 'promise'.

11     var promise: Promise<string | null>;
           ~~~~~~~

node_modules/find-java-home/dist/index.d.ts:15:9 - error TS2323: Cannot redeclare exported variable 'promise'.

15     var promise: Promise<string | null>;
```

it sound slike a problem in the library itself. if nto can you advise what needs to be done to fix the issu eon my side please?

**Comment by apupier** [comment]
but it is not failing on an upgrade on another project https://github.com/camel-tooling/camel-lsp-client-vscode/pull/599

**Comment by jsdevel** [comment]
@apupier is this still an issue?  i'm assuming there may be something that's not configured correctly in your project.  please re-open if this is an issue with the library.

**Comment by apupier** [comment]
thsi is still an issue.
Duplicate bug was opened (for the same project) https://github.com/jsdevel/node-find-java-home/issues/33
