### ISSUE TITLE
node findJavaHome.js returns Null value with oraclelinux8-openjdk11.0.15 

### ISSUE THREAD

**Issue by divishav** [jsdevel/node-find-java-home#37]
I am using oraclelinux8-openjdk11.0.15 and running **node findJavaHome.js:** is giving Null value and below error:
TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
#30 0.565     at new NodeError (node:internal/errors:372:5)
#30 0.565     at _write (node:internal/streams/writable:299:11)
#30 0.565     at Socket.Writable.write (node:internal/streams/writable:334:10)
#30 0.565     at /usr/src/app/Content_Connect/node_modules/java/findJavaHome.js:6:18
#30 0.565     at /usr/src/app/Content_Connect/node_modules/find-java-home/dist/index.js:103:21
#30 0.565     at step (/usr/src/app/Content_Connect/node_modules/find-java-home/dist/index.js:46:23)
#30 0.565     at Object.next (/usr/src/app/Content_Connect/node_modules/find-java-home/dist/index.js:27:53)
#30 0.565     at fulfilled (/usr/src/app/Content_Connect/node_modules/find-java-home/dist/index.js:18:58) {
#30 0.565   code: 'ERR_STREAM_NULL_VALUES'

Java is correctly installed and running $JAVA_HOME gives the following path: /usr/lib/jvm/java-11-openjdk-11.0.15.0.10-2.el8_6.x86_64

Why findJavaHome not able to find it?
This is happening only with oraclelinux8-openjdk11.0.15, it works fine in oraclelinux8-openjdk11.0.14
![findjavahome](https://user-images.githubusercontent.com/49013921/169989580-c4d8fbe2-a975-4083-8b8d-e3ac3b8e119a.PNG)

**Comment by jsdevel** [comment]
please submit a PR

**Comment by morph85** [comment]
In my case i had "java" installed in rhel8 but not "javac" which require installing package ($ yum install java-devel).

**Comment by divishav** [comment]
Javac was not installed on the jdk. So the installation was failing. Issue was resolved after installating javac
